apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
  - name: myapp
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31000
